apiVersion: yarotsky.me/v1alpha1
kind: Application
metadata:
  name: application-sample
spec:
  image:
    repository: "git.home.yarotsky.me/vlad/dashboard"
    versionStrategy: "SemVer"
    semver:
      constraint: "^0"
    updateSchedule: "@every 5m"
  ports:
  - name: "http"
    containerPort: 8080
  - name: "metrics"
    containerPort: 8192
  - name: "listener-tcp"
    containerPort: 22000
  - name: "listener-udp"
    containerPort: 22000
    protocol: "UDP"
  ingress:
    host: "dashboard.home.yarotsky.me"
  loadBalancer:
    host: "things.home.yarotsky.me"
    ports: ["listener-tcp", "listener-udp"]
