apiVersion: yarotsky.me.yarotsky.me/v1alpha1
kind: Application
metadata:
  labels:
    app.kubernetes.io/name: application
    app.kubernetes.io/instance: application-sample
    app.kubernetes.io/part-of: application-controller
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: application-controller
  name: application-sample
spec:
  # TODO(user): Add fields here
